### ISSUE TITLE
Bump to 1.0

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/chunked-dc-js#17]
Is there anything missing to this implementation? Otherwise, I think we can bump it to 1.0.

**Comment by dbrgn** [comment]
Only thing I wondered about is whether a streamable interface would be beneficial.

**Comment by dbrgn** [comment]
But you're right, let's bump to v1.0.0!

**Comment by dbrgn** [comment]
4acc00dc0c9a24c1e33157a7eebe0092b80b258e

https://www.npmjs.com/package/chunked-dc

**Comment by lgrahl** [comment]
Good point but we can add a streamable interface later when needed.
(btw. I'm thinking of a streamable interface in anyrtc)
