### ISSUE TITLE
Use WebWorker?

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/chunked-dc-js#22]
If we can't get rid of the long blocking due to copying procedures (which are sadly necessary for Uint8Array), it might make sense to use a dedicated WebWorker for this.

**Comment by beaulac** [comment]
I've been using this library in a WebWorker,  
```js
importScripts('chunked-dc.es5.polyfill.js');
// ...
var chunker = new chunkedDc.Chunker(0, file, chunkSize);
var unchunker = new chunkedDc.Unchunker();
```
It works :+1:

**Comment by lgrahl** [comment]
Yup. I think we can close this since it doesn't require any modification to the code.

**Comment by dbrgn** [comment]
@beaulac nice to hear that other people than me are using the library :slightly_smiling_face:
